$.jStorage.set('language', {
	it : {
		restart : 'riavvia',
		generateInverse : 'calcola relazioni inverse',
		autoExpand : 'espandi automaticamente le relazioni',
		autoSameAs : 'calcola relazioni inverse di tipo sameAs',
		autoCollectImages : 'raccogli le immagini durante la navigazione',
		autoDrawMap : 'geolocalizza le risorse',
		noName : 'denominazione non trovata',
		addUri : 'inserisci una uri',
		findResource : 'cerca una risorsa',
		choose : 'scegli...',
		resourceMissing : 'risorsa non trovata',
		resourceMissingDoc : 'non sono state trovate proprietà di tipo literal per la risorsa per la lingua impostata o la risorsa non è momentaneamente disponibile nell\'endpoint',
		options : 'OPZIONI',
		endpointNotConfigured : 'nessun endpoint configurato per la risorsa',
		endpointNotConfiguredSoInternal : 'nessun endpoint configurato per la risorsa, generazione grafo temporaneo',
		impostaUnaURI : 'imposta un uri, esegui una ricerca \no scegli tra gli esempi proposti',
		example : 'esempio',
		noIe : 'Siamo spiacenti ma attualmente Internet Explorer non &egrave; totalmente supportato.',
		enpointNotAvailable : 'errore: endpoint non disponibile',
		enpointNotAvailableOrSLow : 'errore: endpoint non disponibile o richiesta scaduta',
		imagesNotFound : 'nessuna immagine per le risorse aperte',
		mapNotFound : 'nessuna mappa per le riorse aperte',
		propsNotFound : 'nessuna propriet&agrave; trovata',
		propsFound : 'propriet&agrave; trovate',
		showResource : 'evidenza la risorsa',
		zoomIn : 'ingrandisci',
		showConsole : 'mostra la console delle ricerche (sperimentale)',
		executeThisQuery : 'esegui la query SPARQL in una nuova finestra',
		moreInfoOnThis : 'maggiori informazioni su questa risorsa',
		simpleSearch : 'ricerca semplice',
		simpleSearchDescription : 'DBpedia.org e Freebase consentono di interrogare le proprie risorse per parola chiave.<br /><br />Scegliendo un dataset e digitando almeno tre lettere di una parola chiave è possibile trovare gli URI delle risorse che si vuole esplorare.',
		insertUri : 'inserisci un URI',
		insertUriDescription : 'LodLive è in grado di analizzare e rappresentare risorse RDF anche se non supportate da un EndPoint per l\'accesso SPARQL.<br /><br />Inserendo un qualsiasi URI ad una risorsa RDF è possibile esplorarne contenuti e relazioni.',
		insertData : 'esplora i tuoi dati',
		liveLodLive : 'Scegliendo un endpoint tra quelli configurati è possibile navigare la risorsa e ricavare, attraverso delle query SPARQL preimpostate, non solo le proprietà dirette, ma anche tutte le proprietà inverse indipendentemente dal dataset di appartenenza.'
	},
	en : {
		restart : 'restart',
		generateInverse : 'generate inverse relations',
		autoExpand : 'auto-expand mode',
		autoSameAs : 'generate inverse sameAs relations',
		autoCollectImages : 'collect images during browsing',
		autoDrawMap : 'geolocalize resources',
		noName : 'no title provided',
		addUri : 'insert an URI',
		findResource : 'find resources',
		choose : 'choose...',
		resourceMissing : 'resource not found',
		resourceMissingDoc : 'literal values not found or the resource is missing or not available in the endpoint',
		options : 'OPTIONS',
		endpointNotConfigured : 'no endpoint configured for the resource',
		endpointNotConfiguredSoInternal : 'no endpoint configured for the resource, generating temporary graph',
		impostaUnaURI : 'inert an uri, make a query or choose one of the examples provided',
		example : 'example',
		noIe : 'Sorry but Internet Explorer is not totally supported.',
		enpointNotAvailable : 'error: endpoint not available',
		enpointNotAvailableOrSLow : 'error: endpoint not available or the request timed out',
		imagesNotFound : 'no images for the opened resources',
		mapNotFound : 'no maps for the opened resources',
		propsNotFound : 'nothing found',
		propsFound : 'properties found',
		showResource : 'highlight the resource',
		zoomIn : 'zoom in',
		showConsole : 'show console (experimental)',
		executeThisQuery : 'execute the SPARQL query in a new window',
		moreInfoOnThis : 'more info on this resource',
		simpleSearch : 'simple search',
		simpleSearchDescription : 'DBpedia.org and Freebase allow  their resources to be queried through keywords.<br/><br/>You will be able to find the URIs of the resources  you want to explore by choosing a dataset and typing at least three letters of a keyword for it.',
		insertUri : 'insert URI',
		insertUriDescription : 'LodLive is able to analyse and "show"  RDF resources even when they are  not supported by a SPARQL access EndPoint.<br/><br/>By entering any URI to an RDF resource,  you will be able to explore contents and relationships.',
		insertData : 'browse your data'
	}
});

$.jStorage.set('selectedLanguage', 'en');
