$.jStorage.set('language', {
	it : {
		restart : 'riavvia',
		generateInverse : 'calcola relazioni inverse',
		autoExpand : 'espandi automaticamente le relazioni',
		autoSameAs : 'calcola relazioni inverse di tipo sameAs',
		autoCollectImages : 'raccogli le immagini durante la navigazione',
		autoDrawMap : 'geolocalizza le risorse',
		noName : 'denominazione non trovata',
		addUri : 'inserisci una uri',
		findResource : 'cerca una risorsa',
		choose : 'scegli...',
		resourceMissing : 'risorsa non trovata',
		resourceMissingDoc : 'non sono state trovate proprietà di tipo literal per la risorsa per la lingua impostata o la risorsa non è momentaneamente disponibile nell\'endpoint',
		options : 'OPZIONI',
		endpointNotConfigured : 'nessun endpoint configurato per la risorsa',
		endpointNotConfiguredSoInternal : 'nessun endpoint configurato per la risorsa, generazione grafo temporaneo',
		impostaUnaURI : 'imposta un uri, esegui una ricerca \no scegli tra gli esempi proposti',
		example : 'esempio',
		noIe : 'Siamo spiacenti ma attualmente Internet Explorer non &egrave; totalmente supportato.',
		enpointNotAvailable : 'errore: endpoint non disponibile',
		enpointNotAvailableOrSLow : 'errore: endpoint non disponibile o richiesta scaduta',
		imagesNotFound : 'nessuna immagine per le risorse aperte',
		mapNotFound : 'nessuna mappa per le riorse aperte',
		propsNotFound : 'nessuna propriet&agrave; trovata',
		propsFound : 'propriet&agrave; trovate',
		showResource : 'evidenza la risorsa',
		zoomIn : 'ingrandisci',
		showConsole : 'mostra la console delle ricerche (sperimentale)',
		executeThisQuery : 'esegui la query SPARQL in una nuova finestra',
		moreInfoOnThis : 'maggiori informazioni su questa risorsa',
		simpleSearch : 'ricerca semplice',
		simpleSearchDescription : 'DBpedia.org e Freebase consentono di interrogare le proprie risorse per parola chiave.<br /><br />Scegliendo un dataset e digitando almeno tre lettere di una parola chiave è possibile trovare gli URI delle risorse che si vuole esplorare.',
		insertUri : 'inserisci un URI',
		insertUriDescription : 'LodLive è in grado di analizzare e rappresentare risorse RDF anche se non supportate da un EndPoint per l\'accesso SPARQL.<br /><br />Inserendo un qualsiasi URI ad una risorsa RDF è possibile esplorarne contenuti e relazioni.',
		insertData : 'esplora i tuoi dati',
		liveLodLive : 'Scegliendo un endpoint tra quelli configurati è possibile navigare la risorsa e ricavare, attraverso delle query SPARQL preimpostate, non solo le proprietà dirette, ma anche tutte le proprietà inverse indipendentemente dal dataset di appartenenza.',
		centerClose : 'centra e chiudi le altre risorse',
		openOnline : 'visualizza la risorsa online',
		openRelated : 'espandi tutte le relazioni',
		removeResource : 'rimuovi questo box',
		noImage:'immagine non disponibile',
		connectedResources:'risorse collegate'
	},
	en : {
		restart : 'restart',
		generateInverse : 'generate inverse relations',
		autoExpand : 'auto-expand mode',
		autoSameAs : 'generate inverse sameAs relations',
		autoCollectImages : 'collect images during browsing',
		autoDrawMap : 'geolocalize resources',
		noName : 'no title provided',
		addUri : 'insert an URI',
		findResource : 'find resources',
		choose : 'choose...',
		resourceMissing : 'resource not found',
		resourceMissingDoc : 'literal values not found or the resource is missing or not available in the endpoint',
		options : 'OPTIONS',
		endpointNotConfigured : 'no endpoint configured for the resource',
		endpointNotConfiguredSoInternal : 'no endpoint configured for the resource, generating temporary graph',
		impostaUnaURI : 'insert an uri, make a query or choose one of the examples provided',
		example : 'example',
		noIe : 'Sorry but Internet Explorer is not totally supported.',
		enpointNotAvailable : 'error: endpoint not available',
		enpointNotAvailableOrSLow : 'error: endpoint not available or the request timed out',
		imagesNotFound : 'no images for the opened resources',
		mapNotFound : 'no maps for the opened resources',
		propsNotFound : 'nothing found',
		propsFound : 'properties found',
		showResource : 'highlight the resource',
		zoomIn : 'zoom in',
		showConsole : 'show console (experimental)',
		executeThisQuery : 'execute the SPARQL query in a new window',
		moreInfoOnThis : 'more info on this resource',
		simpleSearch : 'simple search',
		simpleSearchDescription : 'DBpedia.org and Freebase allow  their resources to be queried through keywords.<br/><br/>You will be able to find the URIs of the resources  you want to explore by choosing a dataset and typing at least three letters of a keyword for it.',
		insertUri : 'insert URI',
		insertUriDescription : 'LodLive is able to analyse and "show"  RDF resources even when they are  not supported by a SPARQL access EndPoint.<br/><br/>By entering any URI to an RDF resource,  you will be able to explore contents and relationships.',
		insertData : 'browse your data',
		centerClose : 'focus on the resource',
		openOnline : 'access the online resource',
		openRelated : 'expand related resources',
		removeResource : 'remove this box',
		noImage:'image not available',
		connectedResources:'connected resources'
	},
		fr : {
		restart : 'redémarrer',
		generateInverse : 'générer les relations inverses',
		autoExpand : 'mode auto-expansion',
		autoSameAs : 'générer les relations inverses sameAs',
		autoCollectImages : 'récupération des images pendant la navigation',
		autoDrawMap : 'géolocaliser les ressources',
		noName : 'sans titre',
		addUri : 'insérer une URI',
		findResource : 'chercher ressources',
		choose : 'choisir...',
		resourceMissing : 'ressource inconnue',
		resourceMissingDoc : 'valeurs littérales inconnues ou ressource inconnue ou ressource inaccessible au point d\'accès',
		options : 'OPTIONS',
		endpointNotConfigured : 'aucun endpoint n\'est configuré pour cette ressource',
		endpointNotConfiguredSoInternal : 'aucun endpoint n\'est configuré pour la ressource , génération d\'un graphe temporaire',
		impostaUnaURI : 'saisir une URI, faire une recherche ou choisir un des exemples fournis',
		example : 'exemple',
		noIe : 'Désolé, Internet Explorer n\'est pas complètement supporté',
		enpointNotAvailable : 'erreur: point d\'accès non disponible',
		enpointNotAvailableOrSLow : 'erreur: point d\'accès non disponible ou délai dépassé',
		imagesNotFound : 'aucune image pour les ressources en cours',
		mapNotFound : 'aucune carte pour les ressources en cours',
		propsNotFound : 'aucun résultat',
		propsFound : 'propriétés trouvées',
		showResource : 'surligner la ressource',
		zoomIn : 'zoomer',
		showConsole : 'afficher la console (expérimental)',
		executeThisQuery : 'exécuter la requête SPARQL query dans une nouvelle fenêtre',
		moreInfoOnThis : 'plus d\'informations sur cette ressource',
		simpleSearch : 'simple recherche',
		simpleSearchDescription : 'DBpedia.org et Freebase autorise les recherches par mots-clés.<br/><br/>Vous pouvez trouver les URI des ressources que vous cherchez en choisissant un jeu de données et en tapant au moins trois lettres d\'un mot clé .',
		insertUri : 'insérer une URI',
		insertUriDescription : 'LodLive is capable d\'analyser et de montrer des ressources RDF, y compris quand elles ne sont pas supportées par un point d\'accès SPARQL<br/><br/>En entrant une URI vers une ressource RDF,  vous serez capable d\'explorer son contenu et ses relations.',
		insertData : 'parcourir vos données',
		centerClose : 'se recentrer sur cette ressource',
		openOnline : 'accéder à la ressource en ligne',
		openRelated : 'déployer toutes les ressources associées',
		removeResource : 'retirer cette entrée',
		noImage:'image indisponible',
		connectedResources:'ressources reliées'
	}
});

$.jStorage.set('selectedLanguage', 'en');
